export * from './checkTap';
export * from './checkWord';
export * from './generateTileMatrix';
export * from './getFallDownTime';
export * from './removeChosenTiles';
export * from './score';
export * from './shuffleTiles';
export * from './sounds';
export * from './updateTilePosition';
